### ISSUE TITLE
Options are not updated after adding user secrets

### ISSUE THREAD

**Issue by Kreuz41** [k-paul-acct/minimal-telegram-bot#4]
If we add user secrets like this:
``` C#
var builder = BotApplication.CreateBuilder(args);
builder.Configuration.AddUserSecrets<Program>();
var bot = builder.Build();
```
In the configuration, the token value is changed to what is used in the secrets, but the application cannot build because it takes the token value from `BotApplicationBuilderOptions` which are not updated after adding secrets
![Screenshot from 2024-10-04 19-46-54](https://github.com/user-attachments/assets/218de99d-79a2-496c-858b-da3d8e25aa14)
![Screenshot from 2024-10-04 19-45-54](https://github.com/user-attachments/assets/13c66673-3d8a-4bab-89e1-8ccc7d40e2fe)

**Comment by k-paul-acct** [comment]
Configuration from user secrets are used by default in the development environment, so for now you can use configuration as it is without adding user secrets manually. Later, I will investigate this issue and probably will fix this in the nest versions.
